# Generated by Django 4.2 on 2023-05-18 15:11

import ImageUploadapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='images/', validators=[ImageUploadapp.models.image_validation])),
                ('binary_image', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
