# Generated by Django 4.2 on 2023-05-18 15:21

import ImageUploadapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploadapp', '0002_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[ImageUploadapp.models.image_validation]),
        ),
    ]
